# Generated by Django 3.2.8 on 2022-01-31 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0006_alter_useraccount_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_confirmed',
            new_name='is_varified',
        ),
    ]
