# Generated by Django 3.2.8 on 2022-02-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0007_rename_is_confirmed_useraccount_is_varified'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='auth_provider',
            field=models.CharField(default='email', max_length=255),
        ),
    ]
