# Generated by Django 3.2.8 on 2022-02-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0008_useraccount_auth_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='is_varified',
            new_name='is_verified',
        ),
    ]
