# Generated by Django 3.2.8 on 2022-01-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220113_1638'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalCategory',
        ),
    ]
