# Generated by Django 3.2.8 on 2022-01-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_historicalcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='thumbnail',
            field=models.TextField(blank=True, default='ProductsDefault.jpg', max_length=100, null=True, verbose_name='Thumbnail'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, default='ProductsDefault.jpg', null=True, upload_to='Products/%Y/%m/%d/', verbose_name='Thumbnail'),
        ),
    ]
