# Generated by Django 3.2.8 on 2022-01-13 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220113_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='active',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)]),
        ),
    ]
