# Generated by Django 3.2.8 on 2022-01-13 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220113_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='active',
            field=models.IntegerField(choices=[(1, 'Live'), (2, 'Draft'), (3, 'Hidden')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='thumbnail',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.IntegerField(choices=[(1, 'Live'), (2, 'Draft'), (3, 'Hidden')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='Products/%Y/%m/%d/', verbose_name='Thumbnail'),
        ),
    ]
