# Generated by Django 3.2.8 on 2022-01-15 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220115_1125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='ImageGalary',
        ),
    ]
