# Generated by Django 3.2.8 on 2022-01-15 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_variants_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegalary',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagegalary', related_query_name='imagegalary', to='products.variants'),
        ),
    ]
