# Generated by Django 3.2.8 on 2022-01-27 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_imagegalary_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variants',
            options={'verbose_name_plural': 'Variants'},
        ),
    ]
