# Generated by Django 3.2.8 on 2022-01-28 15:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_variants_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='image',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='imagegalary',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='imagegalary',
            name='cover',
            field=models.ImageField(blank=True, upload_to='Products/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='imagegalary',
            name='image1',
            field=models.ImageField(blank=True, upload_to='Products/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='imagegalary',
            name='image2',
            field=models.ImageField(blank=True, upload_to='Products/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='imagegalary',
            name='image3',
            field=models.ImageField(blank=True, upload_to='Products/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='imagegalary',
            name='image4',
            field=models.ImageField(blank=True, upload_to='Products/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='imagegalary',
            name='image5',
            field=models.ImageField(blank=True, upload_to='Products/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='variants',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='variants',
            name='image_galary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.imagegalary'),
        ),
        migrations.AddField(
            model_name='variants',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
